# Generated by Django 4.2.23 on 2025-08-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('What_we_do', models.CharField(max_length=200)),
                ('our_mission', models.TextField(blank=True, max_length=10000)),
                ('our_goals', models.TextField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=10000)),
            ],
        ),
    ]
