# Generated by Django 4.2.23 on 2025-08-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
    ]
